name = "NationalWeightedActivityUnitWrapper"
uuid = "58dad789-f56a-4ab3-a66f-c15139bf9cbe"
version = "0.1.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Downloads = "1"
julia = "1.10"
